# Generated by Django 5.2 on 2025-04-21 07:09

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.user_directory_path,
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Masculin"),
                            ("F", "Féminin"),
                            ("O", "Autre"),
                            ("N", "Préfère ne pas préciser"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Sexe",
                    ),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin", "Administrateur"),
                            ("gerant", "Gérant"),
                            ("gestionnaire", "Gestionnaire"),
                            ("employe", "Employé"),
                        ],
                        max_length=12,
                        null=True,
                        verbose_name="Role",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a", "Section A"),
                            ("b", "Section B"),
                            ("c", "Section C"),
                            ("toutes", "Toutes"),
                        ],
                        max_length=6,
                        null=True,
                        verbose_name="Section",
                    ),
                ),
                (
                    "prison",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paris", "Paris"),
                            ("lyon", "Lyon"),
                            ("marseille", "Marseille"),
                            ("cergy", "Cergy"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Prison",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="customuser_set", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customuser_permissions_set",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
