# Generated by Django 5.2 on 2025-04-22 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("update_profile", "Modification du profil"),
                            ("password_change", "Changement de mot de passe"),
                            ("create", "Création de compte"),
                            ("delete", "Suppression de compte"),
                            ("otp_request", "Demande de code OTP"),
                            ("otp_validate", "Validation OTP"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
