# Generated by Django 5.2 on 2025-04-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prison',
            field=models.CharField(blank=True, choices=[('paris', 'Paris'), ('lyon', 'Lyon'), ('marseille', 'Marseille'), ('cergy', 'Cergy')], max_length=20, null=True, verbose_name='Prison (legacy)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prison_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.prison', verbose_name='Prison'),
        ),
    ]
