# Generated by Django 5.2 on 2025-04-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Prison_id',
            field=models.CharField(blank=True, choices=[('paris', 'Paris'), ('lyon', 'Lyon'), ('marseille', 'Marseille'), ('cergy', 'Cergy')], max_length=10, null=True, verbose_name='Prison ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire'), ('employe', 'Employé')], max_length=12, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, choices=[('a', 'Section A'), ('b', 'Section B'), ('c', 'Section C'), ('toutes', 'Toutes')], max_length=6, null=True, verbose_name='Section'),
        ),
    ]
