# Generated by Django 5.1.7 on 2025-03-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_naissance",
            field=models.DateField(blank=True, null=True),
        ),
    ]
