# Generated by Django 5.2 on 2025-04-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_prison_alter_customuser_prison_customuser_prison_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='prison',
            name='nb_detenus',
            field=models.IntegerField(default=0),
        ),
    ]
