# Generated by Django 5.2 on 2025-04-19 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_prison_id_customuser_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Prison_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='prison',
            field=models.CharField(blank=True, choices=[('paris', 'Paris'), ('lyon', 'Lyon'), ('marseille', 'Marseille'), ('cergy', 'Cergy')], max_length=10, null=True, verbose_name='Prison'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
