# Generated by Django 5.1.7 on 2025-04-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_date_naissance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="gender",
            new_name="sexe",
        ),
    ]
