# Generated by Django 5.2 on 2025-04-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_prison_id_customuser_prison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('gerant', 'Gérant'), ('gestionnaire', 'Gestionnaire'), ('employe', 'Employé')], max_length=12, null=True, verbose_name='Role'),
        ),
    ]
