# Generated by Django 5.2 on 2025-04-27 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistique", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date et heure de création de la statistique.",
                verbose_name="Date de création",
            ),
        ),
    ]
