# Generated by Django 5.2 on 2025-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistique', '0002_stat_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='prison_id',
            field=models.CharField(blank=True, help_text='ID de la prison associée à cette statistique.', max_length=100, null=True, verbose_name='ID Prison'),
        ),
    ]
