# Generated by Django 5.2 on 2025-04-21 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("porte", "Porte Automatique"),
                            ("lumiere", "Lumière"),
                            ("camera", "Caméra"),
                            ("chauffage", "Chauffage"),
                            ("climatisation", "Climatisation"),
                            ("paneau d'affichage", "paneau d'affichage"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Role",
                    ),
                ),
                ("coord_x", models.FloatField()),
                ("coord_y", models.FloatField()),
                (
                    "etat",
                    models.CharField(
                        blank=True,
                        choices=[("on", "On"), ("off", "Off")],
                        max_length=3,
                        null=True,
                        verbose_name="Etat",
                    ),
                ),
                (
                    "connection",
                    models.CharField(
                        blank=True,
                        choices=[("wifi", "Wifi"), ("filaire", "Filaire")],
                        max_length=20,
                        null=True,
                        verbose_name="Connection",
                    ),
                ),
                ("consomation", models.IntegerField()),
                ("valeur_actuelle", models.CharField(blank=True)),
                ("valeur_cible", models.CharField(blank=True)),
                ("durabilité", models.IntegerField(default=0)),
                (
                    "maintenance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en panne", "En Panne"),
                            ("fonctionnel", "Fonctionnel"),
                        ],
                        default="fonctionnel",
                        max_length=20,
                        null=True,
                        verbose_name="Maintenance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("porte", "Porte Automatique"),
                            ("lumiere", "Lumière"),
                            ("camera", "Caméra"),
                            ("chauffage", "Chauffage"),
                            ("climatisation", "Climatisation"),
                            ("paneau d'affichage", "paneau d'affichage"),
                        ],
                        max_length=50,
                        verbose_name="Type d'objet",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "etat",
                    models.CharField(
                        choices=[("on", "On"), ("off", "Off")],
                        max_length=50,
                        verbose_name="État",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "objet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="object.object",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'objet",
                "verbose_name_plural": "Logs d'objets",
                "ordering": ["-date"],
            },
        ),
    ]
