# Generated by Django 5.1.7 on 2025-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Objet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("porte", "Porte Automatique"),
                            ("lumiere", "Lumière"),
                            ("camera", "Caméra"),
                            ("chauffage", "Chauffage"),
                        ],
                        max_length=9,
                        null=True,
                        verbose_name="Role",
                    ),
                ),
                ("coord_x", models.FloatField()),
                ("coord_y", models.FloatField()),
                (
                    "etat",
                    models.CharField(
                        blank=True,
                        choices=[("on", "On"), ("off", "Off")],
                        max_length=3,
                        null=True,
                        verbose_name="Etat",
                    ),
                ),
            ],
        ),
    ]
