# Generated by Django 5.1.7 on 2025-04-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("object", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Objet",
            new_name="Object",
        ),
    ]
