# Generated by Django 5.2 on 2025-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("object", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="durabilité",
            field=models.IntegerField(default=100),
        ),
    ]
