# Generated by Django 5.2 on 2025-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_alter_object_durabilité'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='Prison_id',
            field=models.CharField(blank=True, choices=[('paris', 'Paris'), ('lyon', 'Lyon'), ('marseille', 'Marseille'), ('cergy', 'Cergy')], max_length=10, null=True, verbose_name='Prison ID'),
        ),
    ]
