# Generated by Django 5.2 on 2025-04-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_rename_objet_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('porte', 'Porte Automatique'), ('lumiere', 'Lumière'), ('camera', 'Caméra'), ('chauffage', 'Chauffage')], max_length=50, verbose_name="Type d'objet")),
                ('nom', models.CharField(max_length=255)),
                ('etat', models.CharField(choices=[('on', 'On'), ('off', 'Off')], max_length=50, verbose_name='État')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='object.object')),
            ],
            options={
                'verbose_name': "Log d'objet",
                'verbose_name_plural': "Logs d'objets",
                'ordering': ['-date'],
            },
        ),
    ]
