# Generated by Django 5.2 on 2025-04-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("object", "0003_add_user_to_object_log"),
        ("object", "0003_object_prison_id"),
    ]

    operations = []
