# Generated by Django 5.2 on 2025-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_merge_20250422_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='type',
            field=models.CharField(blank=True, choices=[('porte', 'Porte Automatique'), ('lumiere', 'Lumière'), ('camera', 'Caméra'), ('thermostat', 'Thermostat'), ('ventilation', 'Ventilation'), ("paneau d'affichage", "paneau d'affichage")], max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='objetlog',
            name='type',
            field=models.CharField(choices=[('porte', 'Porte Automatique'), ('lumiere', 'Lumière'), ('camera', 'Caméra'), ('thermostat', 'Thermostat'), ('ventilation', 'Ventilation'), ("paneau d'affichage", "paneau d'affichage")], max_length=50, verbose_name="Type d'objet"),
        ),
    ]
