# Generated by Django 5.2 on 2025-04-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0005_alter_object_type_alter_objetlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetlog',
            name='prison_id',
            field=models.CharField(blank=True, choices=[('paris', 'Paris'), ('lyon', 'Lyon'), ('marseille', 'Marseille'), ('cergy', 'Cergy')], max_length=10, null=True, verbose_name='Prison ID'),
        ),
    ]
