# Generated by Django 5.2 on 2025-04-26 23:30
from django.db import migrations

def update_object_logs_prison_id(apps, schema_editor):
    ObjetLog = apps.get_model('object', 'ObjetLog')
    Object = apps.get_model('object', 'Object')
    
    # Pour chaque log qui a un objet associé, copier la Prison_id de l'objet
    for log in ObjetLog.objects.filter(objet__isnull=False, prison_id__isnull=True):
        try:
            obj = Object.objects.get(pk=log.objet_id)
            if hasattr(obj, 'Prison_id'):  # Vérifie que l'attribut existe bien
                log.prison_id = obj.Prison_id
                log.save()
        except Object.DoesNotExist:
            pass
        except Exception as e:
            # En cas d'autres erreurs, on les ignore simplement
            # et on continue avec le prochain log
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('object', '0006_add_prison_id_to_objetlog'),
    ]

    operations = [
        migrations.RunPython(update_object_logs_prison_id, migrations.RunPython.noop),
    ]
