# Generated by Django 5.2 on 2025-04-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0007_update_objetlog_prison_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='consomation',
            field=models.IntegerField(help_text="Consommation électrique de l'objet"),
        ),
    ]
