# Generated by Django 5.2 on 2025-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0008_alter_object_consomation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='consomation',
            field=models.FloatField(help_text="Consommation électrique de l'objet"),
        ),
    ]
